import type {
  DeviceType,
  DeviceStyle,
  DeviceColor,
  VectorOverlayConfig,
  PlayStoreBadgesConfig,
  TextOverlay,
} from "../types/device";
import type { Background } from "../store/useEditorStore";

export interface PlayStoreTemplate {
  id: string;
  name: string;
  category: "Fintech" | "Productivity" | "Fitness" | "Social" | "Minimal" | "Banner" | "E-Commerce";
  description: string;
  previewGradient: [string, string];
  deviceType: DeviceType;
  deviceStyle: DeviceStyle;
  deviceColor: DeviceColor;
  canvasWidth: number | null;
  canvasHeight: number | null;
  background: Background;
  vectorOverlay: VectorOverlayConfig;
  badges: PlayStoreBadgesConfig;
  headline: Partial<TextOverlay>;
  subtitle: Partial<TextOverlay>;
  frameProps: {
    scale: number;
    rotation: number;
    rotateX: number;
    rotateY: number;
    skewX: number;
    skewY: number;
    offsetX: number;
    offsetY: number;
  };
}

export const PLAYSTORE_TEMPLATES: PlayStoreTemplate[] = [
  {
    id: "cyber-security-glow",
    name: "Cyber Security & Smart Protection",
    category: "Productivity",
    description: "Cyber PCB circuit traces with cyan neon glow, 3D tilted phone & floating holographic shield",
    previewGradient: ["#0284c7", "#09090b"],
    deviceType: "iphone",
    deviceStyle: "realistic",
    deviceColor: "deep-blue",
    canvasWidth: 1080,
    canvasHeight: 2400,
    background: {
      type: "gradient",
      style: "spotlight",
      color1: "#0a1128",
      color2: "#030611",
      angle: 160,
      noise: 0.01,
      pattern: "none",
      vignette: true,
      backdrop: false,
    },
    vectorOverlay: {
      type: "cyber-circuit",
      color: "#ec4899",
      secondaryColor: "#06b6d4",
      opacity: 0.75,
      scale: 1.1,
      positionY: 0.75,
    },
    badges: {
      showRating: false,
      ratingScore: 4.9,
      ratingCount: "100K+ Users",
      ratingStyle: "compact-pill",
      ratingPosition: "top",
      showDownloads: false,
      downloadCount: "AI Protected",
      downloadIcon: "shield",
      showFeaturePills: false,
      featurePills: [],
      showFloatingShield: true,
      shieldColor: "#06b6d4",
    },
    headline: {
      text: "PROTECT YOUR\nDIGITAL LIFE",
      fontSize: 60,
      fontFamily: "Poppins",
      fontWeight: 800,
      fill: "#ffffff",
      glow: true,
      glowColor: "#06b6d4",
    },
    subtitle: {
      text: "Real-Time AI Powered Smart Security & Privacy",
      fontSize: 26,
      fontFamily: "Inter",
      fontWeight: 500,
      fill: "#93c5fd",
    },
    frameProps: {
      scale: 1.48,
      rotation: 4,
      rotateX: 14,
      rotateY: 16,
      skewX: 2,
      skewY: -2,
      offsetX: 0,
      offsetY: 70,
    },
  },
  {
    id: "neon-studio-horizon",
    name: "Neon Studio Horizon Glow",
    category: "Productivity",
    description: "Vibrant magenta-cyan neon glow text, 3D studio horizon beam & glossy floor reflection",
    previewGradient: ["#d946ef", "#06b6d4"],
    deviceType: "iphone",
    deviceStyle: "realistic",
    deviceColor: "titanium-dark",
    canvasWidth: 1080,
    canvasHeight: 2400,
    background: {
      type: "gradient",
      style: "spotlight",
      color1: "#1e1035",
      color2: "#05030a",
      angle: 180,
      noise: 0.01,
      pattern: "none",
      vignette: true,
      backdrop: false,
    },
    vectorOverlay: {
      type: "studio-floor",
      color: "#d946ef",
      secondaryColor: "#06b6d4",
      opacity: 0.85,
      scale: 1.1,
      positionY: 0.72,
    },
    badges: {
      showRating: false,
      ratingScore: 4.9,
      ratingCount: "50K+ Users",
      ratingStyle: "compact-pill",
      ratingPosition: "top",
      showDownloads: false,
      downloadCount: "Smart AI",
      downloadIcon: "shield",
      showFeaturePills: false,
      featurePills: [],
      showFloatingShield: false,
    },
    headline: {
      text: "NEXT-GEN APP\nEXPERIENCE",
      fontSize: 58,
      fontFamily: "Poppins",
      fontWeight: 800,
      fill: "#ffffff",
      glow: true,
      glowColor: "#d946ef",
    },
    subtitle: {
      text: "Fast, Intuitive and Designed for Modern Workflows",
      fontSize: 26,
      fontFamily: "Inter",
      fontWeight: 500,
      fill: "#e2e8f0",
    },
    frameProps: {
      scale: 1.48,
      rotation: -3,
      rotateX: 12,
      rotateY: -15,
      skewX: -2,
      skewY: 2,
      offsetX: 0,
      offsetY: 70,
    },
  },
  {
    id: "fintech-dark-ultra",
    name: "Fintech & Crypto Dark",
    category: "Fintech",
    description: "Deep obsidian theme with glowing cyan-purple aurora and security badges",
    previewGradient: ["#0f172a", "#020617"],
    deviceType: "android",
    deviceStyle: "realistic",
    deviceColor: "titanium-dark",
    canvasWidth: 1080,
    canvasHeight: 2400,
    background: {
      type: "gradient",
      style: "spotlight",
      color1: "#0f172a",
      color2: "#020617",
      angle: 145,
      noise: 0.02,
      pattern: "none",
      vignette: true,
      backdrop: false,
    },
    vectorOverlay: {
      type: "aurora",
      color: "#6366f1",
      secondaryColor: "#06b6d4",
      opacity: 0.45,
      scale: 1.1,
      positionY: 0.4,
    },
    badges: {
      showRating: true,
      ratingScore: 4.9,
      ratingCount: "150K+ Ratings",
      ratingStyle: "google-play",
      ratingPosition: "top",
      showDownloads: true,
      downloadCount: "5M+ Downloads",
      downloadIcon: "shield",
      showFeaturePills: true,
      featurePills: [
        { id: "1", text: "🔒 Bank-Grade 256-bit AES", icon: "lock", bg: "rgba(99,102,241,0.25)", textFill: "#c7d2fe" },
        { id: "2", text: "⚡ 0% Transfer Fee", icon: "zap", bg: "rgba(16,185,129,0.25)", textFill: "#a7f3d0" },
      ],
    },
    headline: {
      text: "Smart Banking for the Modern Era",
      fontSize: 54,
      fontFamily: "Poppins",
      fontWeight: 800,
      fill: "#ffffff",
      highlightWord: "Modern Era",
      highlightColor: "#818cf8",
    },
    subtitle: {
      text: "Invest, save, and transfer globally in seconds with zero hidden fees.",
      fontSize: 26,
      fontFamily: "Inter",
      fontWeight: 400,
      fill: "#94a3b8",
    },
    frameProps: {
      scale: 1.55,
      rotation: -3,
      rotateX: 10,
      rotateY: -12,
      skewX: -2,
      skewY: 2,
      offsetX: 0,
      offsetY: 80,
    },
  },
  {
    id: "productivity-ai-grid",
    name: "AI Productivity Matrix",
    category: "Productivity",
    description: "Cyber tech grid lines with emerald glow and ultra-clean typography",
    previewGradient: ["#18181b", "#09090b"],
    deviceType: "android",
    deviceStyle: "realistic",
    deviceColor: "titanium-natural",
    canvasWidth: 1080,
    canvasHeight: 2400,
    background: {
      type: "gradient",
      style: "beam",
      color1: "#18181b",
      color2: "#09090b",
      angle: 180,
      noise: 0.02,
      pattern: "none",
      vignette: true,
      backdrop: false,
    },
    vectorOverlay: {
      type: "modern-grid",
      color: "#8b5cf6",
      secondaryColor: "#10b981",
      opacity: 0.35,
      scale: 1,
      positionY: 0.5,
    },
    badges: {
      showRating: true,
      ratingScore: 4.8,
      ratingCount: "85K+ Reviews",
      ratingStyle: "gold-star",
      ratingPosition: "top",
      showDownloads: true,
      downloadCount: "#1 Product of the Day",
      downloadIcon: "trophy",
      showFeaturePills: true,
      featurePills: [
        { id: "1", text: "✨ Next-Gen AI Engine", icon: "sparkles", bg: "rgba(139,92,246,0.25)", textFill: "#ddd6fe" },
        { id: "2", text: "🚀 10x Faster Workflows", icon: "rocket", bg: "rgba(59,130,246,0.25)", textFill: "#bfdbfe" },
      ],
    },
    headline: {
      text: "Supercharge Your Daily Workflow",
      fontSize: 54,
      fontFamily: "Outfit",
      fontWeight: 800,
      fill: "#ffffff",
      highlightWord: "Supercharge",
      highlightColor: "#a78bfa",
    },
    subtitle: {
      text: "Automate repetitive tasks with intelligence built right in.",
      fontSize: 26,
      fontFamily: "Inter",
      fontWeight: 400,
      fill: "#a1a1aa",
    },
    frameProps: {
      scale: 1.55,
      rotation: 0,
      rotateX: 8,
      rotateY: 0,
      skewX: 0,
      skewY: 0,
      offsetX: 0,
      offsetY: 60,
    },
  },
  {
    id: "fitness-coral-wave",
    name: "Fitness Pulse & Wave",
    category: "Fitness",
    description: "Vibrant high-energy coral orange with fluid waves and flame badges",
    previewGradient: ["#ea580c", "#431407"],
    deviceType: "iphone",
    deviceStyle: "realistic",
    deviceColor: "titanium-dark",
    canvasWidth: 1080,
    canvasHeight: 2400,
    background: {
      type: "gradient",
      style: "radial",
      color1: "#c2410c",
      color2: "#1c1917",
      angle: 135,
      noise: 0.01,
      pattern: "none",
      vignette: true,
      backdrop: false,
    },
    vectorOverlay: {
      type: "waves",
      color: "#fb923c",
      secondaryColor: "#f43f5e",
      opacity: 0.4,
      scale: 1.2,
      positionY: 0.55,
    },
    badges: {
      showRating: true,
      ratingScore: 4.9,
      ratingCount: "200K+ Athletes",
      ratingStyle: "gold-star",
      ratingPosition: "top",
      showDownloads: true,
      downloadCount: "10M+ Workouts Tracked",
      downloadIcon: "flame",
      showFeaturePills: true,
      featurePills: [
        { id: "1", text: "🔥 Real-Time Heart Rate", icon: "heart", bg: "rgba(239,68,68,0.25)", textFill: "#fecaca" },
        { id: "2", text: "📊 AI Workout Plans", icon: "zap", bg: "rgba(249,115,22,0.25)", textFill: "#fed7aa" },
      ],
    },
    headline: {
      text: "Crush Your Goals Every Single Day",
      fontSize: 54,
      fontFamily: "Poppins",
      fontWeight: 800,
      fill: "#ffffff",
      highlightWord: "Crush Your Goals",
      highlightColor: "#fbbf24",
    },
    subtitle: {
      text: "Personalized coaching, meal plans, and instant metrics on your wrist.",
      fontSize: 26,
      fontFamily: "Inter",
      fontWeight: 400,
      fill: "#d6d3d1",
    },
    frameProps: {
      scale: 1.55,
      rotation: 4,
      rotateX: 12,
      rotateY: 14,
      skewX: 2,
      skewY: -2,
      offsetX: 0,
      offsetY: 70,
    },
  },
  {
    id: "social-podium-purple",
    name: "Social Modern Stage",
    category: "Social",
    description: "Sleek glowing podium stage arc with clean isometric device tilt",
    previewGradient: ["#4f46e5", "#1e1b4b"],
    deviceType: "android",
    deviceStyle: "realistic",
    deviceColor: "silver",
    canvasWidth: 1080,
    canvasHeight: 2400,
    background: {
      type: "gradient",
      style: "spotlight",
      color1: "#3730a3",
      color2: "#09090b",
      angle: 160,
      noise: 0.02,
      pattern: "none",
      vignette: true,
      backdrop: false,
    },
    vectorOverlay: {
      type: "stage-podium",
      color: "#818cf8",
      secondaryColor: "#c084fc",
      opacity: 0.5,
      scale: 1.1,
      positionY: 0.6,
    },
    badges: {
      showRating: true,
      ratingScore: 4.9,
      ratingCount: "500K+ Active Users",
      ratingStyle: "compact-pill",
      ratingPosition: "top",
      showDownloads: true,
      downloadCount: "End-to-End Encrypted",
      downloadIcon: "shield",
      showFeaturePills: true,
      featurePills: [
        { id: "1", text: "💬 Ultra-HD Group Calls", icon: "sparkles", bg: "rgba(99,102,241,0.3)", textFill: "#e0e7ff" },
        { id: "2", text: "⚡ Zero Lag Messaging", icon: "zap", bg: "rgba(168,85,247,0.3)", textFill: "#f3e8ff" },
      ],
    },
    headline: {
      text: "Stay Connected with Those Who Matter",
      fontSize: 52,
      fontFamily: "Poppins",
      fontWeight: 700,
      fill: "#ffffff",
      highlightWord: "Connected",
      highlightColor: "#a5b4fc",
    },
    subtitle: {
      text: "Crystal clear audio, video calls, and stories shared instantly.",
      fontSize: 26,
      fontFamily: "Inter",
      fontWeight: 400,
      fill: "#cbd5e1",
    },
    frameProps: {
      scale: 1.55,
      rotation: -2,
      rotateX: 10,
      rotateY: -10,
      skewX: -1,
      skewY: 1,
      offsetX: 0,
      offsetY: 65,
    },
  },
  {
    id: "feature-graphic-landscape",
    name: "Play Store Feature Graphic (1024×500)",
    category: "Banner",
    description: "Official Google Play 1024×500 promotional banner with side-by-side layout",
    previewGradient: ["#1e1b4b", "#0f172a"],
    deviceType: "android",
    deviceStyle: "realistic",
    deviceColor: "titanium-dark",
    canvasWidth: 1024,
    canvasHeight: 500,
    background: {
      type: "gradient",
      style: "spotlight",
      color1: "#312e81",
      color2: "#020617",
      angle: 90,
      noise: 0.02,
      pattern: "none",
      vignette: true,
      backdrop: false,
    },
    vectorOverlay: {
      type: "aurora",
      color: "#6366f1",
      secondaryColor: "#38bdf8",
      opacity: 0.55,
      scale: 1.3,
      positionY: 0.5,
    },
    badges: {
      showRating: true,
      ratingScore: 4.9,
      ratingCount: "Editor's Choice 2026",
      ratingStyle: "google-play",
      ratingPosition: "top",
      showDownloads: true,
      downloadCount: "Over 10 Million Downloads",
      downloadIcon: "trophy",
      showFeaturePills: true,
      featurePills: [
        { id: "1", text: "★ #1 Top Trending App", icon: "star", bg: "rgba(234,179,8,0.25)", textFill: "#fef08a" },
      ],
    },
    headline: {
      text: "The All-In-One Solution for Your Mobile Life",
      fontSize: 36,
      fontFamily: "Poppins",
      fontWeight: 800,
      fill: "#ffffff",
      highlightWord: "All-In-One",
      highlightColor: "#38bdf8",
      x: 0.28,
      y: 0.18,
    },
    subtitle: {
      text: "Fast, secure, and beautifully designed. Download free on Google Play.",
      fontSize: 18,
      fontFamily: "Inter",
      fontWeight: 400,
      fill: "#94a3b8",
      x: 0.28,
      y: 0.52,
    },
    frameProps: {
      scale: 0.65,
      rotation: 6,
      rotateX: 14,
      rotateY: 18,
      skewX: 2,
      skewY: -2,
      offsetX: 240,
      offsetY: 20,
    },
  },
  {
    id: "minimalist-clay-slate",
    name: "Clean Minimalist Clay",
    category: "Minimal",
    description: "Monochrome slate aesthetic with smooth 3D clay device and dot matrix",
    previewGradient: ["#27272a", "#09090b"],
    deviceType: "android",
    deviceStyle: "clay",
    deviceColor: "titanium-dark",
    canvasWidth: 1080,
    canvasHeight: 2400,
    background: {
      type: "gradient",
      style: "none",
      color1: "#1e293b",
      color2: "#020617",
      angle: 180,
      noise: 0.03,
      pattern: "none",
      vignette: true,
      backdrop: false,
    },
    vectorOverlay: {
      type: "dot-matrix",
      color: "#94a3b8",
      secondaryColor: "#64748b",
      opacity: 0.3,
      scale: 1,
      positionY: 0.5,
    },
    badges: {
      showRating: true,
      ratingScore: 5.0,
      ratingCount: "Top Rated",
      ratingStyle: "compact-pill",
      ratingPosition: "top",
      showDownloads: false,
      downloadCount: "Verified Safe",
      downloadIcon: "shield",
      showFeaturePills: true,
      featurePills: [
        { id: "1", text: "Zero Ads • 100% Offline", icon: "check", bg: "rgba(255,255,255,0.08)", textFill: "#f8fafc" },
      ],
    },
    headline: {
      text: "Simplicity in Every Single Detail",
      fontSize: 52,
      fontFamily: "Inter",
      fontWeight: 800,
      fill: "#ffffff",
      highlightWord: "Simplicity",
      highlightColor: "#93c5fd",
    },
    subtitle: {
      text: "Designed for focus, clarity, and uncompromising speed.",
      fontSize: 26,
      fontFamily: "Inter",
      fontWeight: 400,
      fill: "#94a3b8",
    },
    frameProps: {
      scale: 1.55,
      rotation: 0,
      rotateX: 0,
      rotateY: 0,
      skewX: 0,
      skewY: 0,
      offsetX: 0,
      offsetY: 50,
    },
  },
];
